---
- name: Apply System Confiuration Policy
  hosts: all
  become: true
  tasks: 
  - name: Parse System Configuration Policies Applied to Server
    community.general.read_csv:
      path: /policy.csv
      delimiter: ','
    register: policies

  - name: Debug Message, Find path to Policy Name
    ansible.builtin.debug:
      msg: '{{ item.policy_name }}.yml'
    loop: "{{ policies.list}}"
    register: debug_output

  - name: Apply Policies to Machine
    include_tasks: '{{ item.policy_name }}.yml'
    loop: "{{ policies.list}}"

  

  #- name: Execute Policy Playbooks to reconfigure the VM 
