#!/usr/bin/python3
"""
Simplified Ansible Management Utility
"""

# Imports
import click
import os

# Application Route
@click.group()
def cli():
    """ automun - Simplifies Ansible management with module plugin concept, 
    import/export of modules, and consolidate commands for simplified management.
    """

# CREATE COMMAND: Export a Policy Module Template
@click.command("ExportPolicyTemplate")
@click.argument("name", nargs=1)
@click.argument("path", nargs=1)
def export_policy_module_template(path, name):
    """
    Exports ready-to-build policy module template, with example syntax
    """
    print(f"Exporting your policy, {name} to path: {path}")
    # Cache _TEMPLATE_ to /tmp
    os.system(f"mkdir {path}/{name}")
    os.system(f"cp -r ./policyModules/_TEMPLATE_/* {path}/{name}")
    # Rename, {name}
    # Place template in path.
    print("Complete.")

# Import a Policy Module Template, Confirm
@click.command("ImportPolicyModule")
@click.argument("path")
def import_policy_module(path):
    """
    Imports Policy Module for application to managed systems.
    """
    print(f"Your Policy Module is at: {path}" )
# Create Code to open these YML Files as objects.


cli.add_command(export_policy_module_template)
cli.add_command(import_policy_module)

if __name__ == '__main__':
    cli()
