- name: ADD GROUP host WITH GID 401
  ansible.builtin.group:
    name: host
    state: present
    gid: 401
- name: DISALLOW ROOT LOGIN VIA SSH
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "permitRootLogin no"
- name: RESTRICT SSH TO host GROUP
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    insertafter: "EOF"
    line: "AllowGroups host"
- name: ADD vmadmin TO host GROUP
  ansible.builtin.user:
    name: vmadmin
    append: true
    groups: host
- name: Install Cockpit
  ansible.builtin.dnf: 
    name: cockpit
    state: present
- name: Give Cockpit Install Time To Complete
  ansible.builtin.pause:
    minute: 1
- name: Enable Cockpit Service
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: true
    state: started

- name: RESTART SERVER TO CATCH CHANGES
  ansible.builtin.reboot:

